### PR TITLE
add dependabot and github-ci

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by undisbeliever** [comment]
Thank you for starting the github actions integration for my project.

I cannot accept this PR in its current state.
 * The macos and windows jobs do not do anything and should be fixed or removed from `.github/workflows/rust.yml`
 * The linux job does not compile the project.
   * Commit 0185eeb removes the build step.
   * Looking at [the logs](https://github.com/theavege/terrific-audio-driver/actions/runs/11279614519/job/31370745729#step:5:154) for the previous commit - the ubuntu job has a wayland linker error.  I will have to investigate and fix this in a VM over the weekend.
 * None of the rust tests are executed.  I would expect a CI system to run `cargo test`.

I'm fine with the github-ci only compiling and testing the rust code and I will accept this PR if you fix the issues I list above.  I will continue to run my full test suite manually on my Linux PC and Windows Laptop.

---

There are a few reasons I did not setup github actions for this project:

1. Compiling the ca65 and PvSnesLib API tests/examples requires `ca65`, `make`, `python` and `pvsneslib` to be installed on the system and I was unsure how to set them up in a github action (or even if I should compile these tests).
2. Running the ca65 and PvSnesLib API tests/examples requires me to run the tests in a SNES emulator or real console and wait about 10-20 seconds for the tests to complete and display a green screen (indicating the test passes).
   * For anyone interested, the test procedures are documented in the [ca65-api](https://github.com/undisbeliever/terrific-audio-driver/blob/main/audio-driver/ca65-api/README.md#testing) and [pvsneslib-api](https://github.com/undisbeliever/terrific-audio-driver/blob/main/audio-driver/pvsneslib-api/README.md#testing) READMEs.
4. I have an expensive (in terms of CPU time) test that compares the rust bytecode interpreter against the SNES spc700 bytecode interpreter that I implemented as a rust example ([test_bc_interpreter](https://github.com/undisbeliever/terrific-audio-driver/blob/main/crates/compiler/examples/test_bc_interpreter.rs)).  This test is an example as it requires a project file as an argument (allowing me to run the test with multiple project files).
   * `cargo run --example test_bc_interpreter examples/example-project.terrificaudio` (debug build) takes 139 seconds to run on my system (excluding compile time).
   * `cargo run --release --example test_bc_interpreter examples/example-project.terrificaudio` takes 11 seconds to run on my system (excluding compile time).
5. The windows build instructions are complicated.  Not only do you have to compile the `wiz` submodule, you also need to setup the SDL library (for the `sdl2` crate).
   I'm currently using [these instructions for MSVC](https://github.com/Rust-SDL2/rust-sdl2/blob/400e033411b239de10b680f20de800dcb70e9ade/README.md#windows-msvc) because I wanted SDL to be dynamically linked (as recommended on the SDL wiki).  I'm not sure how to convert these steps to github actions.


My current test suite is this:
 * I have a git pre-commit hook that runs `cargo fmt`, `cargo clippy` and `cargo test` to verify I'm not committing any failing tests or rust warnings.
 * Before I push to GitHub I run the full test suite and wait for the various emulator windows to turn green.
   * I use a shell script (that very my environment specific and thus not public) to simplify running the test suite.
 * If I edit the 65816 API, APUIO communications protocol or prepare for a release I also run the SNES tests on a real Super Famicom console.

**Comment by theavege** [comment]
How do you compile Wiz on Linux?

**Comment by undisbeliever** [comment]
> How do you compile Wiz on Linux? I have error "make CFG=debug"

That's problematic.  Wiz used to compile on Linux but now does not because of g++ changes.

I've fixed the 2 compile bugs in a wiz fork and updated the git submodules to point to the wiz fixes.
You should be able to pull the main branch (d5250a9) and it should compile on ubuntu.

I normally compile wiz using `make -j -C wiz`.

**Comment by theavege** [comment]
I have done.

**Comment by undisbeliever** [comment]
Thank you for adding dependabot and github-ci to my project.

**Pull request merged**
